export enum RunnerType {
  UPDATE_COINMARKETCAP_DATA = "@runners/UPDATE_COINMARKETCAP_DATA",
  UPDATE_SYNTH_EXCHANGES = "@runners/UPDATE_SYNTH_EXCHANGESs",
  USDT_DAILY_UPDATER = "@runners/USDT_DAILY_UPDATER",

}
